### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by myl7** [myl7/ssrcli#11]
## A

- [x] SSR integration
- [ ] Speed test & location test
- [ ] PAC support
- [ ] Multi-instance

## B

- [x] pacman-style CLI
- [x] Check test coverage
- [ ] Interactive add
- [ ] HTTP API
- [ ] GUI
